name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy flake8

    - name: Run static type checks (mypy)
      run: |
        mypy app/ tests/

    - name: Run style checks (flake8)
      run: |
        flake8 app/ tests/

    - name: Run tests
      run: |
        pytest